widowx_1:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: Speed
  kinematics_solver_timeout: 0.2
  kinematics_solver_search_resolution: 0.001
widowx_2:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  solve_type: Speed
  kinematics_solver_timeout: 0.2
  kinematics_solver_search_resolution: 0.001
widowx_1_arm_hotend:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  solve_type: Distance
widowx_2_arm_hotend:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.1
  solve_type: Distance